### YamlMime:FAQ
metadata:
  title: 'Preguntas frecuentes: Programación de cursos de Learning Partner en Learn | Microsoft Docs'
  description: 'Preguntas frecuentes: Programación de cursos de Learning Partner en Learn'
  documentationcenter: NA 
  author: micsullivan
  ms.topic: article
  ms.tgt_pltfrm: NA
  ms.workload: NA
  ms.date: 09/01/2020
  ms.author: msulliv
  ms.prod: non-product-specific
    
title: 'Preguntas frecuentes: Programación de cursos de Learning Partner en Learn'
summary: |

  ## Curso dirigido por un instructor

sections:
  - name: Curso dirigido por un instructor
    questions:
      - question: |
          ¿Qué es el servicio de curso dirigido por un instructor de Microsoft Learning Partner?
        answer: |
          Microsoft está lanzando una experiencia de aprendizaje simplificada y optimizada al brindar capacidades de programación de capacitación dirigidas por un instructor en tiempo real a [**Microsoft Learn**](/learn). La integración del programa de cursos en Microsoft Learn permitirá a los estudiantes obtener una vista previa de los cursos de capacitación dirigidos por un instructor ofrecidos por socios de aprendizaje calificados. Una vez que se selecciona un curso, se lo dirigirá directamente al sitio de Learning Partner para completar el registro y el pago.

          Este servicio es actualmente "Vista previa pública" y el registro del curso solo estará disponible en inglés para comenzar. Se agregarán socios de aprendizaje calificados adicionales durante el próximo año. 
          
      - question: |
          ¿Cuáles son los cursos que están disponibles con el servicio de programación de formación dirigida por un instructor de Learning Partner?
        answer: |
          Los siguientes cursos están disponibles con el servicio de programación a partir del 22 de septiembre de 2020. A medida que agreguemos socios de aprendizaje adicionales, se agregarán más cursos con el tiempo
          
          1. Microsoft Azure Fundamentals (2 día)
          2. Microsoft Azure Fundamentals (1 día)
          3. Microsoft Azure Administrator
          4. Developing Solutions for Microsoft Azure
          5. Designing and Implementing an Azure AI Solution
          6. Designing and Implementing a Data Science Solution on Azure
          7. Designing an Azure Data Solution
          8. Implementing an Azure Data Solution
          9. Designing for Identity and Security
          10. Deploying and Configuring Infrastructure
          11. Microsoft Azure Architect Design
          12. Microsoft Azure Security Technologies
          13. Installing Windows 10
          14. Dynamics 365: Power Platform Fundamentals
          15. Office 365 Management
          16. Managing Microsoft 365 Identity and Access
          17. Microsoft 365 Fundamentals
          
      - question: |
          ¿Necesito crear un perfil para usar Microsoft Learn?
        answer: |
          No, no es necesario crear un perfil. Aún puede acceder y utilizar rutas de aprendizaje en línea, [buscar cursos dirigidos por un instructor](/learn/certifications/courses/browse/) y [encontrar un Microsoft Learning Partner por país o región](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country) sin necesidad de crear un perfil.

          Al programar un curso de capacitación dirigido por un instructor en Microsoft Learn, se lo redireccionará al sitio del Learning Partner seleccionado para completar el registro y el pago. Los Learning Partners pueden solicitarle que inicie sesión en su sitio.
          
      - question: |
          ¿Qué funciones están disponibles para mí cuando creo un perfil de Microsoft Learn e inicio sesión?
        answer: |
          - Seguir el progreso en las actividades de aprendizaje
          - Crear y compartir recopilaciones de módulos
          - Guardar marcadores
          - Acumular puntos y logros
          - Utilizar recursos gratuitos de Azure
          - Ver recomendaciones personalizadas
          
      - question: |
          Me registré en un curso con un Learning Partner en Microsoft Learn y no recibí una confirmación del curso. ¿Qué debo hacer? 
        answer: |
          Revise su bandeja de entrada, correo no deseado o spam en busca de un correo electrónico del Learning Partner para el curso en el que se registró.

          Si aún no puede ubicar su correo de confirmación, comuníquese con el Learning Partner en el que programó la clase. El Learning Partner puede ayudar a solucionar cualquier problema de correo y/o validar el registro del curso. La información de contacto del Learning Partner se puede encontrar en: [encontrar un Microsoft Learning Partner por país o región](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Me estoy inscribiendo en un curso y he llegado al sitio de Learning Partner; sin embargo, no hay nada en el carrito.
        answer: |
          Comuníquese con el proveedor de aprendizaje que seleccionó para el curso para resolver el problema. La información de contacto del Learning Partner se puede encontrar en: [encontrar un Microsoft Learning Partner por país o región](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          Necesito cancelar o reprogramar un curso.   
        answer: |
          Póngase en contacto directamente con el Learning Partner. La información de contacto del Learning Partner se puede encontrar en: [encontrar un Microsoft Learning Partner por país o región](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country)
          
      - question: |
          El precio que figura en el sitio de Learn no era el mismo que se indicaba al finalizar la compra. 
        answer: |
          El precio en el sitio o carrito de Learning Partner siempre debe usarse como el precio del artículo, incluso si Learn muestra una cantidad diferente.

          Es posible que el precio final sea diferente en el sitio de Learning Partner o en el carrito, ya que puede haber impuestos incluidos o impuestos que deben calcularse durante el pago. Esto puede incluir el impuesto sobre las ventas y el impuesto al valor agregado (IVA). La cantidad final que pague también puede verse afectada por la ubicación del comprador o el idioma del curso.

          Algunos Learning Partners pueden ofrecer complementos de servicio adicionales durante el proceso de pago. El precio de esos servicios podría cambiar el precio final que ve al pagar.
          
      - question: |
          ¿Cuándo veré cursos en mi país o región? 
        answer: |
          Este es un nuevo servicio que se lanzó en "Vista previa pública" con una pequeña cantidad de Learning Partners calificados para probar la funcionalidad y afinar el proceso. Inicialmente, la programación de los cursos será en inglés y se agregarán socios de aprendizaje adicionales durante los siguientes 12 meses.

      - question: |
          ¿Por qué otros cursos de formación son más o menos costosos que el que quiero asistir?
        answer: |
          Como en cualquier mercado, el precio de la clase lo determina cada Learning Partner. Los socios (Partners) deben proporcionar una experiencia de formación completa en el curso oficial de Microsoft por el precio que figura en la herramienta de programación Microsoft Learn. Los socios (Partners) pueden anunciar productos y servicios adicionales que son opcionales. Si cree que los precios anunciados son engañosos o inexactos, comuníquese con nosotros en el [Programación de cursos dirigidos por un instructor de Learning Partner en el foro de soporte de Learn](https://trainingsupport.microsoft.com/en-us/iltvilt/forum).
          
      - question: |
          El filtro del curso por ubicación, fecha, etc. no funciona correctamente.
        answer: |
          Si el filtro no funciona, actualice su navegador y vuelva a intentarlo. Si cree que los filtros aún no funcionan, puede hacer su pregunta en el [Programación del curso dirigido por un instructor de Learning Partner en el foro de soporte de Learn](https://trainingsupport.microsoft.com/en-us/iltvilt/forum). Es el mejor recurso para buscar y pedir ayuda, informar un problema y obtener asesoramiento.
          
      - question: |
          No puedo encontrar un Learning Partner en mi área.
        answer: |
          Si no ve el Learning Partner o el curso que está buscando, puede encontrar días y horarios adicionales directamente en un sitio de Learning Partner además de lo que se muestra en Microsoft Learn.  Los Learning Partners no están obligados a enumerar los horarios de todas sus clases. Puede encontrar una lista de todos los Microsoft Learning Partners en [encontrar un Microsoft Learning Partner por país o región](/learn/certifications/partners#find-a-microsoft-learning-partner-by-country).

          A medida que lanzamos este nuevo servicio, estamos limitando el número de Learning Partners calificados. Durante el próximo año, se agregarán Learning Partners que cumplan con criterios específicos.
          
      - question: |
          Estuve en el canal de asistencia de Learning Partner y no he recibido ninguna respuesta.
        answer: |
          El Learning Partner es responsable de brindar apoyo relacionado con la programación en su sitio. Puede intentar con diferentes números para el Learning Partner en su sitio web.

          Si aún no puede comunicarse con el Learning Partner, puede publicar su pregunta en el [Programación de cursos dirigidos por un instructor de Learning Partner en el foro de soporte de Learn](https://trainingsupport.microsoft.com/en-us/iltvilt/forum). Es el mejor recurso para pedir ayuda, informar un problema y obtener asesoramiento.
